name:  Cli Build & test
on:
  push:
    paths:
      - 'cli/**'
      - 'go.mod'
      - '.github/workflows/cli**'
    branches:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  build_test:
    strategy:
      fail-fast: true
      matrix:
          os: [Linux, macOS, Windows ]
          include:
            - provider: self-hosted
    runs-on: ${{ matrix.os }}
    steps:
      - name: Basic info
        run: |
          echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
          echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
          whoami
          echo $PATH
          echo $env:PATH
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build
        run: go build -o ocp cli/main.go
      # - name: Test cmd
      #   run: |
      #     cd cli/cmd
      #     go test -cover
      # - name: Test pkg
      #   run: |
      #     cd cli/pkg
      #     go test -cover
