name: SDK GNU Build
on:
    push:
        paths:
            - '.github/workflows/sdk**'
            - 'framework/**'
            - 'starter/**'
            - 'toolkit/**'
            - 'CMake*'
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'
jobs:
    linux-mac-build:
        runs-on: [ self-hosted, Linux]
        steps:
            - name: Basic info
              run: |
                  echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
                  echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                  echo "Tags: ${{ github.event.inputs.tags }}"
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Build 
              run: |
                  chmod 755 clitool
                  ./clitool build -b Debug -c gnu -t all
    mac-build:
        runs-on: [ self-hosted, macOS]
        steps:
            - name: Basic info
              run: |
                  echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
                  echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                  echo "Tags: ${{ github.event.inputs.tags }}"
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Build 
              run: |
                  chmod 755 clitool
                  ./clitool build -b Debug -c gnu12 -t all
    windows-build:
        runs-on: [ self-hosted, Windows]
        steps:
            - name: Basic info
              run: |
                  echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
                  echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                  echo "Tags: ${{ github.event.inputs.tags }}"
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Build 
              run: |
                  C:/msys64/msys2_shell -mingw64 -defterm -here -full-path -no-start -shell bash .github/sdk_msys_build.ps