name: SDK GNU Build
on:
    push:
        paths:
            - '.github/workflows/sdk**'
            - 'framework/**'
            - 'starter/**'
            - 'toolkit/**'
            - 'CMake*'
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'
env:
    CI: false
jobs:
    linux-mac-build:
        strategy:
          fail-fast: true
          matrix:
              os: [Linux, macOS ]
        runs-on: ${{matrix.os}}
        steps:
            - name: Basic info
              run: |
                  echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
                  echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                  echo "Tags: ${{ github.event.inputs.tags }}"
                  echo ${{matrix.os}}
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Build 
              run: |
                  chmod 755 clitool
                  ./clitool build -b Debug -c gnu -t all
    windows-build:
        runs-on: [ self-hosted, Windows]
        steps:
            - name: Basic info
              run: |
                  echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
                  echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                  echo "Tags: ${{ github.event.inputs.tags }}"
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Build 
              run: |
                  C:/msys64/msys2 -c 'chmod 755 clitool'
                  C:/msys64/msys2 -c './clitool build -b Debug -c gnu -t all'